export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_AGE = 'UPDATE_AGE';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_MAIL = 'UPDATE_MAIL';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const STORE_PRODUCTS = 'STORE_PRODUCTS';
export const ENABLE_ALL_PRODUCTS_LOADED = 'ENABLE_ALL_PRODUCTS_LOADED';
